# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
